feat: добавил openapi swagger
Velier12/contractorapi pull request #3
Opened 2024-07-10 09:58 UTC by Velier12

2024-07-10 19:07 UTC, gobaz095 requested changes
А теперь нужно описание для всего писать :)

2024-07-11 02:42 UTC, Velier12 commented
Я надеюсь это описание для сваггера а не джавадоки?

2024-07-11 20:25 UTC, gobaz095 commented
> Я надеюсь это описание для сваггера а не джавадоки?
Конечно, сами ДТО тоже нужно описывать
https://stackoverflow.com/questions/69210490/how-to-annotate-dto-so-that-it-shows-up-in-swaggerui-schema
Сами аннотации
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

2024-07-12 06:58 UTC, gobaz095 commented
И я все также жду тесты с использование testcontainers. Хотя бы на контроллеры и репозитории.

2024-07-16 01:51 UTC, merged